#ifndef CONSTANTS
#define CONSTANTS
#define INITIAL_PROMPT "..............Welcome Back to Acdemia :: Course Registration..............\nLogin type\nEnter Your Choice {1.Admin,2.Professor,3.Student:!"
#define MENU "..........Welcome to Admin Menu..........\n1.Add Student\n2.View Student Details\n3.Add Faculty\n4.View Faculty Details\n5.Activate Student\n6.Block Student\n7.Modify Student Details\n8.Modify Faculty Details\n9.Logout and Exit\nEnter Your choice:"
#define LOGOUT "Logged Out!$"
#define LOGIN_WELCOME "Enter your credentials to loin!"
#define LOGIN_ID "Enter your login id:"
#define LOGIN_ID_DOESNT_EXIT "Invalid login ID$"
#define IN_PASSWORD "Enter your password \n# "
#define INVALID_LOGIN "Invalid Login!$"
#define ADD_NAME "Enter name?"
#define ADD_GENDER "What is the gender?\nEnter M for male, F for female and O for others"
#define WRONG_GENDER "It seems you've enter a wrong gender choice!\nYou'll now be redirected to the main menu!^"
#define ADD_AGE "age?"
#define GET_ID "Enter the ID:"
#define ID_DOESNT_EXIT "No person could be found for the given ID"
#define CHANGE_MENU "Which information would you like to modify?\n1. Name 2. Age 3. Gender \nPress any other key to cancel"
#define NEW_NAME "What's the updated value for name?"
#define NEW_AGE "What's the updated value for age?"
#define NEW_GENDER "What's the updated value for gender?"
#define INVALID_MENU_CHOICE "It seems you've made an invalid menu choice\nYou'll now be redirected to the main menu!^"
#define UPDATE_SUCCESS "The required modification was successfully made!\nYou'll now be redirected to the main menu!^"
#define FACULTY_ID "Enter the faculty id to login!"
#define FACULTY_MENU "..........Welcome to Faculty Menu..........\n1.View Offering Courses\n2.Add New Course\n3.Remove Course from catalog\n4.Update Course Details\n5.Change Password\n6.Logout and Exit\nEnter Your choice:"
#define NEW_PASSWORD "What's the new value for password:?"
#define STUDENT_MENU "..........Welcome to Student Menu..........\n1.View All Courses\n2.Enrol Pic New Course\n3.Drop Course \n4.View Enrolled Course Details\n5.Change Password\n6.Logout and Exit\nEnter Your choice:"
#define ADD_COURSE_ID "What's the course id?"
#define ADD_CREDITS "What's the credits?"
#define ADD_SEATS "What's the total seats?"
#define COURSE_SUCCESS "The course has been successfully added!\nYou'll now be redirected to the main menu!^"
#define COURSE_FAILURE "The course has not  been successfully added!\nYou'll now be redirected to the main menu!^"
#define COURSE_SUCCESS_REMOVE "The course has been successfully delete!\nYou'll now be redirected to the main menu!^"

#endif